# If you need to 'vendor your gems' for deploying your daemons, bundler is a
# great option. Update this Gemfile with any additional dependencies and run
# 'bundle install' to get them all installed. Daemon-kit's capistrano
# deployment will ensure that the bundle required by your daemon is properly
# installed.

source :rubygems

# daemon-kit
gem 'daemon-kit'

# safely (http://github.com/kennethkalmer/safely)
gem 'safely'

gem 'moped', '~> 1.2.5'
gem 'mongoid', '~> 3.0.0'
gem 'pony'
gem 'parse-cron', :git => 'git://github.com/chriskite/parse-cron.git'

# For more information on bundler, please visit http://gembundler.com
